### ISSUE TITLE
Admin Dashboard - Implement "Find Match"

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#10]
The admin can match between volunteer and an organization
## Steps
- [x] Create GUI:
1.  Select volunteer to match
2. Run matching algorithm button
3. Show selection of suitable organizations
4. Submit button 
- [x] Connect the GUI and the DB (using appropriate SQL queries to filter)
- [x] Implement matching algorithm:
1. Research for similar algorithms
2. Implement.

**Points: 10**

**Comment by aryeko** [comment]
Done with manual matching functionality.
Tomer - Please review.

**Comment by tomerach** [comment]
Looking as expected. Now lets implement it considering the volunteer and organization preferences.

**Comment by aryeko** [comment]
Done!
