### ISSUE TITLE
Organization Dashboard - Implement "Started volunteering"

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#11]
The organization can set "started volunteering" to assigned volunteer.
## Steps
- [x] Implement SQL query with the relevant filter (by uniq ID)
- [x] Set "started volunteering" field to true
- [x] Send an Email to the volunteering coordinator with the relevant details

**Points: 2**

**Comment by tomerach** [comment]
Implemented successfully plus testing
