### ISSUE TITLE
Edit homepage content

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#13]
Edit the homepage content to match client's requirements
- [x]  Update alter text
- [x]  Update static content
- [x]  Update collaborations
- [x]  Add button to see all organizations

**Points: 4**

**Comment by aryeko** [comment]
Added the button to get the full organizations list.
Related issue [#53](https://github.com/tomerach/EasyVol-SWE-Project/issues/53)
Submitted on commit [#188](https://github.com/tomerach/EasyVol-SWE-Project/commit/f09a8cdd641631f83efca0f2e2cd278f5ce02497)

**Comment by aryeko** [comment]
Closed by mistake.

**Comment by tomerach** [comment]
Reviewed by me.
Done.
