### ISSUE TITLE
Inception Review

### ISSUE THREAD

**Issue by robi-y** [tomerach/EasyVol-SWE-Project#2]
Hi,
Good work, a few comments
- new production site yet (also link from project list)
- Readme: add at the top a short description of your product
- Inception: interesting gantt, risks: who are your competitors? 
  Good luck (adding @ItamarShDev )

**Comment by aryeko** [comment]
Hi Reuben,

We fixed the readme and the inception.
We didn't understood the first issue, can you elaborate please?

Thanks,
EasyVol team.

**Comment by robi-y** [comment]
no => new, I meant that the link to the live application in the readme points to this: https://demo.reactstarterkit.com/
instead of some start of your applicatiob

**Comment by aryeko** [comment]
All done.
