### ISSUE TITLE
EasyVol-Assignment5-ZFR-Submission

### ISSUE THREAD

**Issue by tomerach** [tomerach/EasyVol-SWE-Project#20]
Hi @ItamarShDev 

Please review our ZFR.

Thanks,
EasyVol Team.

**Comment by robi-y** [comment]
- add us to backlog
- add developer manual

**Comment by tomerach** [comment]
hi @robi-y,
- The developer manual wasn't connected via the proper link.
  We fixed it and now you can find it in the ZFR.
- The US issues will be ready soon.

EasyVol

**Comment by robi-y** [comment]
let me know when to review

**Comment by tomerach** [comment]
Hi @robi-y 

We finished, you can review now.

Thank you,
EasyVol

**Comment by robi-y** [comment]
Nice wiki sidebar
I understand you plan to finish all by iteration 3 and the review all? The common agile practice is to review and complete each story in it's own iteration even if it means doing less stories.
Anyhow - nice work.
