### ISSUE TITLE
Update Organization Registration Forum

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#45]
Please update organization registration forum with the next:
- [x] All student preferences - Work days, work hours, needed skills etc.
- [x] Update forum style to match the volunteers forum.
- [x] Add username and password fields for future signing.
- [x] Update the posted organization object with the new fields.

**Comment by itaysaidoff** [comment]
Everything is done waiting for team to check the code before pushing

**Comment by aryeko** [comment]
Code done. Nice!
