### ISSUE TITLE
**TESTING** - Re-arrange the matching tags

### ISSUE THREAD

**Issue by tomerach** [tomerach/EasyVol-SWE-Project#51]
When there are a lot of tags, the view doesn't look good.

We need to Consider new design. 
One option is to Collapse & Expand the tags to keep the view clean and minimized.

**Comment by aryeko** [comment]
Submitted in commit [#177](https://github.com/tomerach/EasyVol-SWE-Project/commit/493a68ccbf551bbf3142241d2901f474ca140814)
Done.
