### ISSUE TITLE
GUI testing

### ISSUE THREAD

**Issue by aryeko** [tomerach/EasyVol-SWE-Project#54]
Test the web application via GUI with the next tests:
- [x] Login as Admin\Organization
- [x] Add Volunteer\Organization
- [x] Mail to Volunteer\Volunteers
- [x] Find match
- [x] Assign volunteer to organization
- [x] Edit volunteer\organization
- [x] Delete volunteer\organization
- [x] Set feedback to volunteer from organization dashboard - check if feedback is available from admin's dashboard.
- [x] Set "Started volunteering" and "Finished 40 hours" from organization dashboard.

**Comment by aryeko** [comment]
Tested secured login session - **Successful**

**Comment by itaysaidoff** [comment]
I have tested all of the organization dashboard functions including DB connections -**Successful**

**Comment by tomerach** [comment]
Tested the mail functionality and the feedback submit + watch.
Assigning a volunteer to an organization has tested as well - **Successful**

**Comment by amitayben** [comment]
Tested matching functionality via GUI:
1) Added new volunteer with specific preferences
2) Tested fnd match
3) All the attributes are valid, the organization ordering is right.

**Successful**
